spring:
  kafka:
    # Kafka broker addresses
    bootstrap-servers: localhost:9092
    # Producer, 27 config in total
    producer:
      # 默认StringSerializer.class, 默认的序列化类，不能序列化对象，意味着不能发送对象到kafka
      key-serializer: com.fasterxml.jackson.databind.JsonSerializer # 用来序列化对象
      value-serializer: com.fasterxml.jackson.databind.JsonSerializer # 用来序列化对象
    # Consumer, 24 config intotal
    consumer:
      # 从最开的位置读取消息
      auto-offset-reset: earliest
    # 配置监听器
    listener:
      # 开启手动确认消息模式
      ack-mode: manual
    template:
      # 配置模版默认的主题，如果使用sendDefault方法的话，会发到这个topic里面
      default-topic: default-topic