spring:
  kafka:
    # Kafka broker addresses
    bootstrap-servers: localhost:9092
    # Producer, 27 config in total
    # producer:
    # Consumer, 24 config intotal
    consumer:
      # 从最开的位置读取消息
      auto-offset-reset: earliest
    template:
      # 配置模版默认的主题，如果使用sendDefault方法的话，会发到这个topic里面
      default-topic: default-topic